### ISSUE TITLE
Installation on Google Colab

### ISSUE THREAD

**Issue by jhjensen2** [DLHub-Argonne/dlhub_examples#7]
I installed DLhub using pip (pip install dlhub_sdk) on Google Colab, but get the following error when I tried to import (from dlhub_sdk import DLHubClient)

Link to notebook: https://colab.research.google.com/drive/1MilkS4vfCg-eivul2mstCTziADgGpS6M

Error:

ImportError                               Traceback (most recent call last)
<ipython-input-3-babad043129f> in <module>()
----> 1 from dlhub_sdk import DLHubClient

2 frames
/usr/local/lib/python3.6/dist-packages/dlhub_sdk/utils/schemas.py in <module>()
      1 """Utilities for validating against DLHub schemas"""
----> 2 from jsonschema import Draft7Validator, RefResolver
      3 import requests
      4 
      5 _schema_repo = "https://raw.githubusercontent.com/DLHub-Argonne/dlhub_schemas/master/schemas/"

ImportError: cannot import name 'Draft7Validator'

**Comment by WardLT** [comment]
Thanks for pointing this out!

The issue is caused by dlhub_sdk requiring jsonschema version 3.0 or greater and our `setup.py` not specifying a version requirement.

I have changed `dlhub_sdk` to mandate the newer version of jsonschema and will push the change to PyPi later this week.

For now, could you run `pip install jsonschema>=3.0.0 --upgrade` to see if that fixes the issue?

**Comment by jhjensen2** [comment]
Thank you very much for your quick reply! Yes, that fixed it.
